create table public.wallet_losses (
  id bigint generated by default as identity primary key,
  wallet_address text not null unique,
  total_losses numeric not null default 0,
  total_transactions integer not null default 0,
  biggest_loss numeric not null default 0,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

create index wallet_losses_total_losses_idx on wallet_losses(total_losses desc);
